# Generated by Django 3.2.11 on 2022-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
