# Generated by Django 3.2.11 on 2022-01-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='total_sells',
            field=models.IntegerField(default=0),
        ),
    ]
